### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by madiltalay** [omni-us/squeezedet-keras#23]
I am trying to run the following training part:
python ../../scripts/train.py --init ../../main/model/imagenet.h5

But it is neither detecting the 'main', nor the 'tensorflow', giving:
ModuleNotFoundError: no module named main
ModuleNotFoundError: no module named tensorflow

Can you please help?

Thank you!

**Comment by dgtlmoon** [comment]
`pip install tensorflow`

**Comment by madiltalay** [comment]
That problem solved, now I face another problem running the same command:

python scripts/train.py --init main/model/imagenet.h5
Traceback (most recent call last):
  File "scripts/train.py", line 9, in <module>
    from main.model.squeezeDet import  SqueezeDet
ImportError: No module named main.model.squeezeDet

**Comment by Aaronreb** [comment]
> That problem solved, now I face another problem running the same command:
> 
> python scripts/train.py --init main/model/imagenet.h5
> Traceback (most recent call last):
> File "scripts/train.py", line 9, in 
> from main.model.squeezeDet import SqueezeDet
> ImportError: No module named main.model.squeezeDet

Hi, did you solve this problem?

**Comment by mpaluy** [comment]
You have to set `path` correctly.

See: `export PYTHONPATH=path/to/squeezedet` in setup guide
